### ISSUE TITLE
Fill viewport, keeping content within safe areas

### ISSUE THREAD

**Issue by Alanaktion** [Alanaktion/mytube#6]
This is a CSS thing that mostly applies to iPhones in landscape, but can affect any device with a weirdly-shaped display. Basically we want the UI to fill the entire display, while keeping the content from being cropped or inaccessible behind any notches or large rounded corners.

The basics of an implementation could be something like this:

```html
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
```

```css
body {
  padding-bottom: env(safe-area-inset-bottom);
}
nav .container {
  padding-top: env(safe-area-inset-top);
}
.container {
  padding-left: calc(env(safe-area-inset-left) + 1rem);
  padding-right: calc(env(safe-area-inset-right) + 1rem);
}
```

Ideally this should use Tailwind's configured container padding values rather than hard-coding `1rem` for the horizontal padding of the containers.
